---

# Main collection of env. vars to set for all tasks and scripts.
env:
    ####
    #### Global variables used for all tasks
    ####
    # Overrides default location (/tmp/cirrus) for repo clone
    GOPATH: &gopath "/var/tmp/go"
    GOBIN: "${GOPATH}/bin"
    GOCACHE: "${GOPATH}/cache"
    GOSRC: &gosrc "/var/tmp/go/src/github.com/containers/common"
    CIRRUS_WORKING_DIR: *gosrc
    # The default is 'sh' if unspecified
    CIRRUS_SHELL: "/bin/bash"

    ####
    #### image names to test with (double-quotes around names are critical)
    ####
    FEDORA_NAME: "fedora-34"
    IMAGE_SUFFIX: "c6032583541653504"
    FEDORA_CONTAINER_FQIN: "quay.io/libpod/fedora_podman:${IMAGE_SUFFIX}"


# Default, hard-coded max timeout is 2-hours.
timeout_in: 30m  # no need to wait 2-hours before timing out


testing_task:
  alias: testing
  name: "Testing on $FEDORA_NAME"

  container:
    image: "${FEDORA_CONTAINER_FQIN}"

  test_script:
    - make vendor
    - make build
    - make install.tools
    - make validate
    - make test


# Status aggregator for all tests.  This task simply ensures a defined
# set of tasks all passed, and allows confirming that based on the status
# of this task.
success_task:

    depends_on:
        - "testing"

    container:
        image: "${FEDORA_CONTAINER_FQIN}"

    clone_script: &noop mkdir -p "$CIRRUS_WORKING_DIR"
    script: *noop
