---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

downstream_package_name: containers-common
upstream_tag_template: v{version}

packages:
  containers-common-fedora:
    pkg_tool: fedpkg
    specfile_path: rpm/containers-common.spec
  containers-common-centos:
    pkg_tool: centpkg
    specfile_path: rpm/containers-common.spec

actions:
  pre-sync: "bash rpm/update-lib-versions.sh"

jobs:
  - job: copr_build
    trigger: pull_request
    packages: [containers-common-fedora]
    notifications: &ephemeral_build_failure_notification
      failure_comment:
        message: "Ephemeral COPR build failed. @containers/packit-build please check."
    enable_net: true
    targets:
      fedora-development: {}
      fedora-latest: {}
      fedora-eln:
        # Need this to fetch go-md2man which is present in koji envs but not by
        # default on copr envs. Also helps to avoid bundling go-md2man in
        # c/common.
        additional_repos:
          - https://kojipkgs.fedoraproject.org/repos/eln-build/latest/x86_64/

  - job: copr_build
    trigger: pull_request
    packages: [containers-common-centos]
    notifications: *ephemeral_build_failure_notification
    enable_net: true
    targets:
      - epel-9
      - centos-stream-10

  # Run on commit to main branch
  - job: copr_build
    trigger: commit
    notifications:
      failure_comment:
        message: "containers-common-next COPR build failed. @containers/packit-build please check."
    branch: main
    owner: rhcontainerbot
    project: containers-common-next
    enable_net: true

  - job: propose_downstream
    trigger: release
    update_release: false
    packages: [containers-common-fedora]
    dist_git_branches:
      - fedora-development
      - fedora-latest

  - job: propose_downstream
    trigger: release
    update_release: false
    packages: [containers-common-centos]
    dist_git_branches:
      - c10s

  - job: koji_build
    trigger: commit
    packages: [containers-common-fedora]
    dist_git_branches:
      - fedora-all

  - job: bodhi_update
    trigger: commit
    packages: [containers-common-fedora]
    dist_git_branches:
      - fedora-branched # rawhide updates are created automatically
