---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

upstream_tag_template: v{version}

packages:
  containers-common-fedora:
    downstream_package_name: containers-common
    pkg_tool: fedpkg
    specfile_path: rpm/containers-common.spec
  containers-common-centos:
    downstream_package_name: containers-common
    pkg_tool: centpkg
    specfile_path: rpm/containers-common.spec
  containers-common-eln:
    downstream_package_name: containers-common
    specfile_path: rpm/containers-common.spec

actions:
  pre-sync: "bash rpm/update-lib-versions.sh"

jobs:
  - job: copr_build
    trigger: pull_request
    packages: [containers-common-fedora]
    notifications: &packit_failure_notification
      failure_comment:
        message: "[NON-BLOCKING] Packit jobs failed. @containers/packit-build please check."
    enable_net: true
    targets: &fedora_copr_targets
      - fedora-all-x86_64
      - fedora-all-aarch64

  - job: copr_build
    trigger: pull_request
    packages: [containers-common-eln]
    notifications: *packit_failure_notification
    enable_net: true
    targets:
      fedora-eln:
        # Need this to fetch go-md2man which is present in koji envs but not by
        # default on copr envs. Also helps to avoid bundling go-md2man in
        # c/common.
        additional_repos:
          - https://kojipkgs.fedoraproject.org/repos/eln-build/latest/x86_64/

  - job: copr_build
    trigger: pull_request
    packages: [containers-common-centos]
    notifications: *packit_failure_notification
    enable_net: true
    targets: &centos_copr_targets
      - centos-stream-10-x86_64
      - centos-stream-10-aarch64
      - centos-stream-9-x86_64
      - centos-stream-9-aarch64

  # Run on commit to main branch
  - job: copr_build
    trigger: commit
    packages: [containers-common-fedora]
    notifications: *packit_failure_notification
    branch: main
    owner: rhcontainerbot
    project: podman-next
    enable_net: true

  - job: tests
    trigger: pull_request
    packages: [containers-common-fedora]
    notifications: *packit_failure_notification
    targets: *fedora_copr_targets
    enable_net: true
    tf_extra_params:
      environments:
        - artifacts:
          - type: repository-file
            id: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/repo/fedora-$releasever/rhcontainerbot-podman-next-fedora-$releasever.repo

  - job: tests
    trigger: pull_request
    packages: [containers-common-centos]
    notifications: *packit_failure_notification
    targets: *centos_copr_targets
    enable_net: true
    tf_extra_params:
      environments:
        - artifacts:
          - type: repository-file
            id: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/repo/centos-stream-$releasever/rhcontainerbot-podman-next-centos-stream-$releasever.repo

  - job: propose_downstream
    trigger: release
    packages: [containers-common-fedora]
    dist_git_branches: &fedora_targets
      - fedora-all

  - job: propose_downstream
    trigger: release
    packages: [containers-common-centos]
    dist_git_branches:
      - c10s

  # Fedora Koji build
  - job: koji_build
    trigger: commit
    packages: [containers-common-fedora]
    sidetag_group: podman-releases
    # Dependencies are not rpm dependencies, but packages that should go in the
    # same bodhi update
    # Ref: https://packit.dev/docs/fedora-releases-guide/releasing-multiple-packages
    dependents:
      - podman
    dist_git_branches: *fedora_targets
